### ISSUE TITLE
Add to hex?

### ISSUE THREAD

**Issue by nayed** [michalmuskala/format#1]
Hi, could you deploy your package to hex.pm?
I think it's ready :tada:

**Comment by michalmuskala** [comment]
I don't consider this package of production quality, until then, I'll probably won't publish it. There are some issues with formatting floats.
Additionally, there are no tests and I don't feel comfortable publishing a package without a thorough test suite.

If there's interest in pushing this forward, contributions are welcome. I probably won't have cycles to spare on coding for this project in the next month, but I can offer my support for somebody who'd like to contribute.
